version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: llm-dev
    container_name: llm-dev
    volumes:
      - ${PWD}:/app
    restart: on-failure
    working_dir: /app
    command: [ "sleep", "infinity" ]
