version: '3.9'
services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: llm-playground
    container_name: llm-playground
    restart: on-failure
    ports:
      - "3000:80"
    